### PR TITLE
Interrupt handler changes

### PR DESCRIPTION
**Pull request by valeklubomir**
Added analytics for IRQ/FIQ handlers.
Added exception handlers.
Removed some ASSERT macros and replaced with fault handling.

### CODE REVIEW

**Comment by openshwprojects** [comment]
Thanks, is it ready to merge? @btsimonh can you review it?

**Comment by btsimonh** [comment]
so....   this is such a low-level change, if it works, it works.
I tried (and failed) at such a thing :).
I would pull, try and test, but I'm not sure I will have time before I go to Canada.
@valeklubomir - can we have some commands which CAUSE the exceptions, so we can analyse the output?

**Comment by valeklubomir** [comment]
I can try to create test cases which would invoke specific exception. In the application it self.
I have many changes in application I will make PR once these are completed. Without them my APP failes to build.
Finally I have modified SDK so build does not generate warnings. I hope we can keep it that in the future.

**Comment by btsimonh** [comment]
ref SDK, I just issued a PR against both to revert the mqtt changes, now that once mqtt_test is merged, we don't call the mqtt_ functions directly.  Make sure you don't lose the small changes :).

**Comment by btsimonh** [comment]
@valeklubomir - pls also review mqtt_test if you get time.  I have no more 'WARN: TCP' caused by mqtt (one caused by DHCP - which we should address).

**Comment by openshwprojects** [comment]
So, should I merge those N and T interrupt changes now?

**Comment by btsimonh** [comment]
@valeklubomir - what do you think of trying to combine T & N SDKs?
looking at the differences, they are not overly significant....

**Comment by valeklubomir** [comment]
Merging is possible. Most of the differences are in the Makefiles, and linking scripts. There are separate C code files relevant for N and for T.  When I upgraded the T and removed all the Warnings, I compared it with N and most of the changes were already present in N SDK and missing in T SDK. Some of changes I just needed to copy from N SDK to T SDK.

**Comment by btsimonh** [comment]
so it may be possible to build both N and T from the same SDK; possibly with separate libraries (unless we test and find, e.g. librwnx.a is actually better in one....).?

**Comment by valeklubomir** [comment]
I think N SDK and T SDK have some differences which are more result of development history rather than N and T chip differences. 
This would require:
 - create new OpenBK7231 SDK and import new SDK. Merge N and T SDK. I think 90% C/H/ASM files are Identical. Just check and compare. Most of the differences are results of split of N and T SDK and after that not all universal changes were applied to N and T at same time. 
 - We already have conditional definitions for BK7231N and BK7231T used in compilation.
 - Libraries can be for N and T. Linker script will use right one. If libs are identical, no need to have 2 version.
EDIT:
  - Either separate build.sh or parameter entry for chipset N or T.

**Comment by btsimonh** [comment]
I think this is something we should attempt; it would minimise maintenance, and avoid things like the timer thread stack being different (was not the cause of my issues, but could have been!!!).
I did find another non-tuya BK SDK today, but it looks like it may be older (RTT)...

**Comment by valeklubomir** [comment]
If you find some datasheets for BK7231 chip it would be helpful.
I haven't found another SDK yet.
Also the non-tuya SDK could help by simple reviewing it and comparing with tuya to improve it.

**Comment by openshwprojects** [comment]
@valeklubomir , is it ready to merge the interrupt changes? I can't wait to see that new driver for your device

**Comment by valeklubomir** [comment]
I think N SDK has the best base for being universal. There will be much less modification necessary to do.
@openshwprojects You can merge. But you wait for @btsimonh report.
EDIT: I have 2 BK7231T devices running the changes at moment. Stable.

**Comment by btsimonh** [comment]
@valeklubomir - this one: https://github.com/aozima/bk7231_rtt_sdk is interesting because, although old, it has a bunch of things in addition, and some documentation.

**Comment by valeklubomir** [comment]
PS: you can try it yourself. All my changes are in repos and up to date with origin.
https://github.com/valeklubomir/OpenBK7231T_App
https://github.com/valeklubomir/OpenBK7231N
https://github.com/valeklubomir/OpenBK7231T

**Pull request merged**
